services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
  backend:
    image: slib:latest
    ports:
      - "8080:8080"
