name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: 'adopt@1.11'
      - name: Run tests
        run: sbt test
      - name: Run formatting tests
        run: sbt scalafmtCheck
      - name: Run linting tests
        run: sbt 'scalafix --check'

  build-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: 'adopt@1.11'
      - name: Build docker image
        run: sbt Docker/publishLocal
      - name: Clean-up
        run: sbt Docker/clean